### ISSUE TITLE
Can it recover files encrypted by StopDjvu ransomware?

### ISSUE THREAD

**Issue by VQD-BSV** [Demonslay335/CryptoTester#3]
hi
I have files encrypted by ransomware such as .taoy .cdxx etc. Does your tool support it? If so, please try this file and guide me how to restore them?
thank you
[PHÂN LỊCH ĐI CA.xlsx](https://github.com/Demonslay335/CryptoTester/files/14392777/PHAN.L.CH.DI.CA.xlsx)
[Kế hoạch BDSC BIO 3.2020.re.xlsx](https://github.com/Demonslay335/CryptoTester/files/14392778/K.ho.ch.BDSC.BIO.3.2020.re.xlsx)

**Comment by Demonslay335** [comment]
This is a research tool, not a ransomware decryption tool...
